# Generated by Django 4.2 on 2023-04-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
            ],
        ),
    ]
